CREATE TABLE IF NOT EXISTS "Tokens" (
  hash BYTEA PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES "Users" ON DELETE CASCADE,
  expiry TIMESTAMPTZ NOT NULL DEFAULT (NOW()),
  scope TEXT NOT NULL
);
